framework:
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(string:REDIS_URL)%'
